import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig, type Plugin, type ViteDevServer } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, "..");

// How old marketcaps.json may be before a dev-server start refreshes it. The
// exporter exits without a single request when the file is younger than this
// and still covers every symbol, so restarting the dev server stays instant.
const MARKET_CAPS_MAX_AGE_HOURS = 12;

/**
 * Refresh watchlists/marketcaps.json when the dev server starts.
 *
 * Market cap is the one column with no broker behind it, and having to
 * remember a separate `python export_marketcaps.py` before opening the page
 * defeats the point — so the dev server runs it, in the background (the server
 * is up and serving meanwhile) and reloads the page if the file changed.
 */
function marketCaps(): Plugin {
  return {
    name: "financesos:market-caps",
    apply: "serve",
    configureServer(server: ViteDevServer) {
      const venvPython = path.join(PROJECT_ROOT, ".venv/bin/python");
      const python = fs.existsSync(venvPython) ? venvPython : "python3";
      const outFile = path.join(PROJECT_ROOT, "watchlists/marketcaps.json");
      const before = fs.statSync(outFile, { throwIfNoEntry: false })?.mtimeMs;

      const child = spawn(
        python,
        ["export_marketcaps.py", "--max-age-hours", String(MARKET_CAPS_MAX_AGE_HOURS)],
        { cwd: PROJECT_ROOT, stdio: ["ignore", "pipe", "pipe"] },
      );

      const log = (data: Buffer) =>
        String(data)
          .trimEnd()
          .split("\n")
          .forEach((line) => server.config.logger.info(`  market caps: ${line.trim()}`));
      child.stdout.on("data", log);
      child.stderr.on("data", log);

      // A missing interpreter (or missing `requests`) must never take the dev
      // server down with it: the page just keeps the market caps it has.
      child.on("error", (err) =>
        server.config.logger.warn(`  market caps: could not run the exporter (${err.message})`),
      );
      child.on("close", () => {
        const after = fs.statSync(outFile, { throwIfNoEntry: false })?.mtimeMs;
        if (after !== before) server.ws.send({ type: "full-reload" });
      });
    },
  };
}

// Serves the sibling `watchlists/` folder (gitignored, generated by
// export_watchlists.py) as static files at the site root, so the app can
// fetch /index.json and /<slug>.json without a backend or data duplication.
export default defineConfig({
  plugins: [react(), tailwindcss(), marketCaps()],
  publicDir: path.resolve(__dirname, "../watchlists"),
});
